#!/usr/bin/env python3
import sys

path = "frontend/src/AdminApp.jsx"
with open(path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = [
    (
        'import { LogOut, Loader2, TrendingUp, Users, Store, Calendar, ShoppingBag, Package, DollarSign } from "lucide-react";',
        'import { LogOut, Loader2, TrendingUp, Users, Store, Calendar, ShoppingBag, Package, DollarSign, ChevronLeft, Mail, Phone, MapPin } from "lucide-react";',
    ),
    (
        "function OverviewTab({ token }) {",
        'function StatusBadge({ value }) {\n'
        '  const styles = {\n'
        '    pending: { bg: "#F2F2F2", fg: colors.creamDim },\n'
        '    confirmed: { bg: "#FDE9DC", fg: colors.hairline },\n'
        '    completed: { bg: "#E3F3E8", fg: "#2F7A45" },\n'
        '    cancelled: { bg: "#FBE4E4", fg: "#C0392B" },\n'
        '    unpaid: { bg: "#F2F2F2", fg: colors.creamDim },\n'
        '    paid: { bg: "#E3F3E8", fg: "#2F7A45" },\n'
        '    failed: { bg: "#FBE4E4", fg: "#C0392B" },\n'
        '    refunded: { bg: "#FDE9DC", fg: colors.hairline },\n'
        '  };\n'
        '  const s = styles[value] || { bg: "#F2F2F2", fg: colors.creamDim };\n'
        '  return (\n'
        '    <span\n'
        '      className="text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full"\n'
        '      style={{ background: s.bg, color: s.fg }}\n'
        '    >\n'
        '      {value}\n'
        '    </span>\n'
        '  );\n'
        '}\n\n'
        'function UserDetailView({ token, userId, onBack }) {\n'
        '  const [data, setData] = useState(null);\n'
        '  const [loading, setLoading] = useState(true);\n'
        '  const [error, setError] = useState(null);\n\n'
        '  useEffect(() => {\n'
        '    setLoading(true);\n'
        '    apiFetch(`/admin/users/${userId}`, { headers: { Authorization: `Bearer ${token}` } })\n'
        '      .then(setData)\n'
        '      .catch(() => setError("Couldn\'t load this user."))\n'
        '      .finally(() => setLoading(false));\n'
        '  }, [token, userId]);\n\n'
        '  if (loading) return <div className="pt-16 flex justify-center"><Loader2 size={28} className="animate-spin" color={colors.creamDim} /></div>;\n'
        '  if (error || !data) return <p className="text-sm text-center py-10" style={{ color: colors.creamDim }}>{error}</p>;\n\n'
        '  const { user, salons, bookings } = data;\n\n'
        '  return (\n'
        '    <div className="px-4 py-4 space-y-4">\n'
        '      <button onClick={onBack} className="flex items-center gap-1 text-sm font-semibold" style={{ color: colors.hairline }}>\n'
        '        <ChevronLeft size={16} /> Back to users\n'
        '      </button>\n\n'
        '      <div className="rounded-2xl p-4 flex items-center gap-3" style={{ border: `2px solid ${colors.hairline}` }}>\n'
        '        {user.profile_photo_url ? (\n'
        '          <img src={user.profile_photo_url} alt="" className="w-14 h-14 rounded-full object-cover" style={{ border: `2px solid ${colors.hairline}` }} />\n'
        '        ) : (\n'
        '          <div className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background: colors.panelLight }}>\n'
        '            <Users size={22} color={colors.hairline} />\n'
        '          </div>\n'
        '        )}\n'
        '        <div>\n'
        '          <p className="text-lg font-bold" style={{ color: colors.cream, fontFamily: FONT_DISPLAY }}>{user.name}</p>\n'
        '          <p className="text-xs uppercase tracking-wide font-semibold" style={{ color: colors.hairline }}>{user.role}</p>\n'
        '        </div>\n'
        '      </div>\n\n'
        '      <div className="rounded-2xl p-4 space-y-2" style={{ border: `2px solid ${colors.hairline}` }}>\n'
        '        <p className="text-sm flex items-center gap-2" style={{ color: colors.cream }}><Mail size={14} color={colors.creamDim} /> {user.email}</p>\n'
        '        {user.phone && <p className="text-sm flex items-center gap-2" style={{ color: colors.cream }}><Phone size={14} color={colors.creamDim} /> {user.phone}</p>}\n'
        '        {(user.address_city || user.address_state) && (\n'
        '          <p className="text-sm flex items-center gap-2" style={{ color: colors.cream }}>\n'
        '            <MapPin size={14} color={colors.creamDim} /> {[user.address_city, user.address_state].filter(Boolean).join(", ")}\n'
        '          </p>\n'
        '        )}\n'
        '        <p className="text-xs" style={{ color: colors.creamDim }}>Joined {new Date(user.created_at).toLocaleDateString()}</p>\n'
        '        {user.referral_code && <p className="text-xs" style={{ color: colors.creamDim }}>Referral code: {user.referral_code}</p>}\n'
        '      </div>\n\n'
        '      {salons && salons.length > 0 && (\n'
        '        <div className="rounded-2xl p-4" style={{ border: `2px solid ${colors.hairline}` }}>\n'
        '          <p className="text-sm font-bold mb-2" style={{ color: colors.cream }}>Salon{salons.length > 1 ? "s" : ""}</p>\n'
        '          {salons.map((s) => (\n'
        '            <p key={s.id} className="text-sm" style={{ color: colors.cream }}>{s.name} <span style={{ color: colors.creamDim }}>· {s.category}</span></p>\n'
        '          ))}\n'
        '        </div>\n'
        '      )}\n\n'
        '      <div className="rounded-2xl p-4" style={{ border: `2px solid ${colors.hairline}` }}>\n'
        '        <p className="text-sm font-bold mb-3" style={{ color: colors.cream }}>\n'
        '          {user.role === "owner" ? "Bookings received" : "Booking history"} ({bookings.length})\n'
        '        </p>\n'
        '        {bookings.length === 0 && <p className="text-xs" style={{ color: colors.creamDim }}>No bookings yet.</p>}\n'
        '        <div className="space-y-3">\n'
        '          {bookings.map((b) => (\n'
        '            <div key={b.id} className="pb-3" style={{ borderBottom: `1px solid ${colors.panelLight}` }}>\n'
        '              <div className="flex items-center justify-between mb-1">\n'
        '                <p className="text-sm font-semibold" style={{ color: colors.cream }}>{b.service_name}</p>\n'
        '                <p className="text-sm font-bold" style={{ color: colors.cream }}>{naira(b.service_price)}</p>\n'
        '              </div>\n'
        '              <p className="text-xs mb-1.5" style={{ color: colors.creamDim }}>\n'
        '                {user.role === "owner" ? b.customer_name : b.salon_name} · {new Date(b.created_at).toLocaleDateString()}\n'
        '              </p>\n'
        '              <div className="flex gap-1.5">\n'
        '                <StatusBadge value={b.status} />\n'
        '                <StatusBadge value={b.payment_status} />\n'
        '              </div>\n'
        '            </div>\n'
        '          ))}\n'
        '        </div>\n'
        '      </div>\n'
        '    </div>\n'
        '  );\n'
        '}\n\n'
        'function UsersTab({ token }) {\n'
        '  const [users, setUsers] = useState(null);\n'
        '  const [error, setError] = useState(null);\n'
        '  const [selectedUserId, setSelectedUserId] = useState(null);\n'
        '  const [filter, setFilter] = useState("all");\n\n'
        '  useEffect(() => {\n'
        '    apiFetch("/admin/users", { headers: { Authorization: `Bearer ${token}` } })\n'
        '      .then(setUsers)\n'
        '      .catch(() => setError("Couldn\'t load users."));\n'
        '  }, [token]);\n\n'
        '  if (selectedUserId) {\n'
        '    return <UserDetailView token={token} userId={selectedUserId} onBack={() => setSelectedUserId(null)} />;\n'
        '  }\n\n'
        '  if (error) return <p className="text-sm text-center py-10" style={{ color: colors.creamDim }}>{error}</p>;\n'
        '  if (!users) return <div className="pt-16 flex justify-center"><Loader2 size={28} className="animate-spin" color={colors.creamDim} /></div>;\n\n'
        '  const filtered = users.filter((u) => filter === "all" || u.role === filter);\n\n'
        '  return (\n'
        '    <div className="px-4 py-4">\n'
        '      <div className="flex gap-2 mb-4">\n'
        '        {["all", "customer", "owner"].map((f) => (\n'
        '          <button\n'
        '            key={f}\n'
        '            onClick={() => setFilter(f)}\n'
        '            className="px-3 py-1.5 rounded-full text-xs font-semibold capitalize"\n'
        '            style={{ background: filter === f ? colors.hairline : colors.panelLight, color: filter === f ? "#fff" : colors.cream }}\n'
        '          >\n'
        '            {f === "all" ? "All" : `${f}s`}\n'
        '          </button>\n'
        '        ))}\n'
        '      </div>\n'
        '      <div className="space-y-2">\n'
        '        {filtered.map((u) => (\n'
        '          <button\n'
        '            key={u.id}\n'
        '            onClick={() => setSelectedUserId(u.id)}\n'
        '            className="w-full text-left rounded-2xl p-3.5 flex items-center justify-between tap-glass"\n'
        '            style={{ border: `2px solid ${colors.hairline}` }}\n'
        '          >\n'
        '            <div>\n'
        '              <p className="text-sm font-bold" style={{ color: colors.cream }}>{u.name}</p>\n'
        '              <p className="text-xs" style={{ color: colors.creamDim }}>{u.email}</p>\n'
        '            </div>\n'
        '            <div className="text-right">\n'
        '              <p className="text-[10px] font-bold uppercase tracking-wide" style={{ color: colors.hairline }}>{u.role}</p>\n'
        '              <p className="text-xs" style={{ color: colors.creamDim }}>\n'
        '                {u.role === "owner" ? `${u.salonsOwned} salon${u.salonsOwned === 1 ? "" : "s"}` : `${u.bookingsMade} booking${u.bookingsMade === 1 ? "" : "s"}`}\n'
        '              </p>\n'
        '            </div>\n'
        '          </button>\n'
        '        ))}\n'
        '      </div>\n'
        '    </div>\n'
        '  );\n'
        '}\n\n'
        'function BookingsTab({ token }) {\n'
        '  const [bookings, setBookings] = useState(null);\n'
        '  const [error, setError] = useState(null);\n\n'
        '  useEffect(() => {\n'
        '    apiFetch("/admin/bookings", { headers: { Authorization: `Bearer ${token}` } })\n'
        '      .then(setBookings)\n'
        '      .catch(() => setError("Couldn\'t load bookings."));\n'
        '  }, [token]);\n\n'
        '  if (error) return <p className="text-sm text-center py-10" style={{ color: colors.creamDim }}>{error}</p>;\n'
        '  if (!bookings) return <div className="pt-16 flex justify-center"><Loader2 size={28} className="animate-spin" color={colors.creamDim} /></div>;\n\n'
        '  return (\n'
        '    <div className="px-4 py-4 space-y-3">\n'
        '      {bookings.length === 0 && <p className="text-sm text-center py-10" style={{ color: colors.creamDim }}>No bookings yet.</p>}\n'
        '      {bookings.map((b) => (\n'
        '        <div key={b.id} className="rounded-2xl p-3.5" style={{ border: `2px solid ${colors.hairline}` }}>\n'
        '          <div className="flex items-center justify-between mb-1">\n'
        '            <p className="text-sm font-bold" style={{ color: colors.cream }}>{b.customer_name} → {b.salon_name}</p>\n'
        '            <p className="text-sm font-bold" style={{ color: colors.cream }}>{naira(b.service_price)}</p>\n'
        '          </div>\n'
        '          <p className="text-xs mb-2" style={{ color: colors.creamDim }}>\n'
        '            {b.service_name} · {new Date(b.created_at).toLocaleDateString()} · commission {naira(b.commission_amount)}\n'
        '          </p>\n'
        '          <div className="flex gap-1.5">\n'
        '            <StatusBadge value={b.status} />\n'
        '            <StatusBadge value={b.payment_status} />\n'
        '          </div>\n'
        '        </div>\n'
        '      ))}\n'
        '    </div>\n'
        '  );\n'
        '}\n\n'
        "function OverviewTab({ token }) {",
    ),
    (
        '        {[\n'
        '          { id: "overview", label: "Overview" },\n'
        '          { id: "products", label: "Products" },\n'
        '          { id: "orders", label: "Orders" },\n'
        '        ].map((t) => (',
        '        {[\n'
        '          { id: "overview", label: "Overview" },\n'
        '          { id: "users", label: "Users" },\n'
        '          { id: "bookings", label: "Bookings" },\n'
        '          { id: "products", label: "Products" },\n'
        '          { id: "orders", label: "Orders" },\n'
        '        ].map((t) => (',
    ),
    (
        '      {tab === "overview" && <OverviewTab token={auth.token} />}\n'
        '      {tab === "products" && <ProductsTab token={auth.token} />}\n'
        '      {tab === "orders" && <OrdersTab token={auth.token} />}',
        '      {tab === "overview" && <OverviewTab token={auth.token} />}\n'
        '      {tab === "users" && <UsersTab token={auth.token} />}\n'
        '      {tab === "bookings" && <BookingsTab token={auth.token} />}\n'
        '      {tab === "products" && <ProductsTab token={auth.token} />}\n'
        '      {tab === "orders" && <OrdersTab token={auth.token} />}',
    ),
]

for old, new in replacements:
    count = content.count(old)
    if count != 1:
        print(f"FAILED: anchor not found exactly once (found {count})")
        print("----- anchor -----")
        print(old[:300])
        print("------------------")
        sys.exit(1)
    content = content.replace(old, new)

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print("OK: patched AdminApp.jsx with Users + Bookings tabs and drill-down")
print("Review with: git diff")
print('Then: git add -A && git commit -m "Admin: add clickable Users and Bookings tabs" && git push')
