// Nigeria states and their major cities, used for location-based search and salon signup.
// Structured so more countries can be added later (each entry: { state, cities }).
export const NIGERIA_LOCATIONS = [
  { state: "Abia", cities: ["Umuahia", "Aba", "Ohafia"] },
  { state: "Adamawa", cities: ["Yola", "Mubi", "Jimeta"] },
  { state: "Akwa Ibom", cities: ["Uyo", "Eket", "Ikot Ekpene"] },
  { state: "Anambra", cities: ["Awka", "Onitsha", "Nnewi"] },
  { state: "Bauchi", cities: ["Bauchi", "Azare", "Misau"] },
  { state: "Bayelsa", cities: ["Yenagoa", "Brass", "Sagbama"] },
  { state: "Benue", cities: ["Makurdi", "Gboko", "Otukpo"] },
  { state: "Borno", cities: ["Maiduguri", "Biu", "Bama"] },
  { state: "Cross River", cities: ["Calabar", "Ikom", "Ogoja"] },
  { state: "Delta", cities: ["Asaba", "Warri", "Sapele"] },
  { state: "Ebonyi", cities: ["Abakaliki", "Afikpo", "Onueke"] },
  { state: "Edo", cities: ["Benin City", "Ekpoma", "Auchi"] },
  { state: "Ekiti", cities: ["Ado-Ekiti", "Ikere", "Ikole"] },
  { state: "Enugu", cities: ["Enugu", "Nsukka", "Awgu"] },
  { state: "Gombe", cities: ["Gombe", "Kumo", "Billiri"] },
  { state: "Imo", cities: ["Owerri", "Orlu", "Okigwe"] },
  { state: "Jigawa", cities: ["Dutse", "Hadejia", "Gumel"] },
  { state: "Kaduna", cities: ["Kaduna", "Zaria", "Kafanchan"] },
  { state: "Kano", cities: ["Kano", "Wudil", "Gwarzo"] },
  { state: "Katsina", cities: ["Katsina", "Funtua", "Daura"] },
  { state: "Kebbi", cities: ["Birnin Kebbi", "Argungu", "Yauri"] },
  { state: "Kogi", cities: ["Lokoja", "Okene", "Kabba"] },
  { state: "Kwara", cities: ["Ilorin", "Offa", "Omu-Aran"] },
  { state: "Lagos", cities: ["Ikeja", "Lagos Island", "Lekki", "Surulere", "Ajah", "Yaba"] },
  { state: "Nasarawa", cities: ["Lafia", "Keffi", "Akwanga"] },
  { state: "Niger", cities: ["Minna", "Bida", "Kontagora"] },
  { state: "Ogun", cities: ["Abeokuta", "Ijebu Ode", "Sagamu"] },
  { state: "Ondo", cities: ["Akure", "Ondo Town", "Owo"] },
  { state: "Osun", cities: ["Osogbo", "Ile-Ife", "Ilesa"] },
  { state: "Oyo", cities: ["Ibadan", "Ogbomoso", "Oyo Town"] },
  { state: "Plateau", cities: ["Jos", "Bukuru", "Pankshin"] },
  { state: "Rivers", cities: ["Port Harcourt", "Bonny", "Obio-Akpor"] },
  { state: "Sokoto", cities: ["Sokoto", "Tambuwal", "Wurno"] },
  { state: "Taraba", cities: ["Jalingo", "Wukari", "Bali"] },
  { state: "Yobe", cities: ["Damaturu", "Potiskum", "Nguru"] },
  { state: "Zamfara", cities: ["Gusau", "Kaura Namoda", "Talata Mafara"] },
  { state: "FCT (Abuja)", cities: ["Abuja", "Gwagwalada", "Kuje"] },
];
